//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat_to_Callsheet_Tool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatCustIdX {
            get {
                return ((string)(this["ChatCustIdX"]));
            }
            set {
                this["ChatCustIdX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatCustIdY {
            get {
                return ((string)(this["ChatCustIdY"]));
            }
            set {
                this["ChatCustIdY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatCustNameX {
            get {
                return ((string)(this["ChatCustNameX"]));
            }
            set {
                this["ChatCustNameX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatCustNameY {
            get {
                return ((string)(this["ChatCustNameY"]));
            }
            set {
                this["ChatCustNameY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatProblemX {
            get {
                return ((string)(this["ChatProblemX"]));
            }
            set {
                this["ChatProblemX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatProblemY {
            get {
                return ((string)(this["ChatProblemY"]));
            }
            set {
                this["ChatProblemY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetCustIdX {
            get {
                return ((string)(this["CallsheetCustIdX"]));
            }
            set {
                this["CallsheetCustIdX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetCustIdY {
            get {
                return ((string)(this["CallsheetCustIdY"]));
            }
            set {
                this["CallsheetCustIdY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetCustNameX {
            get {
                return ((string)(this["CallsheetCustNameX"]));
            }
            set {
                this["CallsheetCustNameX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetCustNameY {
            get {
                return ((string)(this["CallsheetCustNameY"]));
            }
            set {
                this["CallsheetCustNameY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetProblemX {
            get {
                return ((string)(this["CallsheetProblemX"]));
            }
            set {
                this["CallsheetProblemX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetProblemY {
            get {
                return ((string)(this["CallsheetProblemY"]));
            }
            set {
                this["CallsheetProblemY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetInProgressX {
            get {
                return ((string)(this["CallsheetInProgressX"]));
            }
            set {
                this["CallsheetInProgressX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetInProgressY {
            get {
                return ((string)(this["CallsheetInProgressY"]));
            }
            set {
                this["CallsheetInProgressY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetSaveX {
            get {
                return ((string)(this["CallsheetSaveX"]));
            }
            set {
                this["CallsheetSaveX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetSaveY {
            get {
                return ((string)(this["CallsheetSaveY"]));
            }
            set {
                this["CallsheetSaveY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetNewX {
            get {
                return ((string)(this["CallsheetNewX"]));
            }
            set {
                this["CallsheetNewX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetNewY {
            get {
                return ((string)(this["CallsheetNewY"]));
            }
            set {
                this["CallsheetNewY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetResetX {
            get {
                return ((string)(this["CallsheetResetX"]));
            }
            set {
                this["CallsheetResetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CallsheetResetY {
            get {
                return ((string)(this["CallsheetResetY"]));
            }
            set {
                this["CallsheetResetY"] = value;
            }
        }
    }
}
